on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .vscode/**
      - .workspace/**
      - "*.md"
      - "**/.env.development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ci-image -f .devcontainer/Dockerfile .

      - name: Build Wasm
        run: docker run --rm -v $(pwd):/workspace ci-image make build

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: ./build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: archive
          path: ./build

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
